[package]
org = "fraudalert"
name = "fraudbackend"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[dependencies]
ballerina.sql = "1.8.0"
ballerinax.mysql = "1.16.1"
ballerina.crypto = "1.3.0"



[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-j"
version = "8.4.0"
path = "./lib/mysql-connector-j-8.4.0.jar"
modules = ["."]