
pythonBin = "./fraudbackend/venv/bin/python3"
mlScriptPath = "./fraudML/classify.py"
ocrScriptPath = "./fraudML/extract_text.py"
useOcrApi = true

dbHost = "127.0.0.1"
dbUser = "root"
dbPassword = "Enter Your mysql password here"
dbName = "job_fraud_db"
dbPort = 3306

